### ISSUE TITLE
Add workflow for yamllint

### ISSUE THREAD

**Issue by juancarlosjr97** [juancarlosjr97/github-actions-workflows-to-rule-them-all#31]
Add yamllint, for example

```yaml
- name: Validate YAML
  uses: ibiqlik/action-yaml-lint@v3
  with:
    config_file: '.yamllint'
```
