### ISSUE TITLE
Add Security Scan with Trivy

### ISSUE THREAD

**Issue by juancarlosjr97** [juancarlosjr97/github-actions-workflows-to-rule-them-all#35]
Security is a non-negotiable. Trivy scans your container images and dependencies for vulnerabilities before they become a problem.

Use it for:

Keeping your Docker images secure.
Identifying vulnerable dependencies before deployment.

```yaml
- name: Security Scan
  uses: aquasecurity/trivy-action@v0.3.0
  with:
    image-ref: myapp:latest
```
